name: env_dare
channels:
  - defaults
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.12.9
  - pytorch==2.4.0
  - pytorch-cuda=12.4
  - matplotlib
  - scikit-image
  - scikit-learn
  - scipy
  - zarr=2.12.0
  - diffusers==0.18.2
  - numba
  - dill=0.3.5.1
  - einops=0.4.1
  - hydra-core
  - wandb=0.13.3
  - pandas
  - ray-core
  - pip:
    - ortools==9.12.4544